[package]
name = "algorithmica"
version = "0.1.4"
authors = ["AbrarNitk <abrar.nitk@gmail.com>"]
edition = "2018"
description = "Rust Algorithms"
license = "MIT"
include = ["src/**/*", "Cargo.toml"]
repository = "https://github.com/AbrarNitk/algorithmica"

[dependencies]
