[workspace]
members = [
    "algorithmica", 
    "redblackbst", 
    "rust-challenges", 
    "rust-fundamentals", 
    "rust-networks/tcp-cli-server",
    "rust-networks/ws-chat-server",
    "sample-projects"
]
